# Generated by Django 3.2.15 on 2022-10-15 23:09

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('specialty', models.IntegerField(choices=[(1, 'Ischemic Heart Disease'), (2, 'Heart Failure'), (3, 'Coronary Care'), (4, 'Arrythmia'), (5, 'Congenital Heart Disease'), (6, 'Other')], default=1)),
                ('nurse_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
                ('description', models.TextField()),
                ('nurse_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
