# Generated by Django 3.2.15 on 2022-10-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
