# Generated by Django 3.2.15 on 2022-10-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0002_alter_specialty_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[(1, 'IHD'), (2, 'HF'), (3, 'CCU')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
