# Generated by Django 3.2.15 on 2022-10-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0003_alter_nurseprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, unique=True),
        ),
    ]
