# Generated by Django 3.2.15 on 2022-10-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0006_auto_20221010_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseprofile',
            name='year_qualified',
        ),
    ]
