# Generated by Django 3.2.15 on 2022-10-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0007_alter_nurseprofile_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='specialty',
            field=models.IntegerField(choices=[('Ischemic Heart Disease', 'IHD'), ('Heart Failure', 'HF'), ('Coronary Care', 'CC'), ('Arrythmia', 'ARY'), ('Congenital Heart Disease', 'CHD'), ('Other', 'Other')], default=1),
        ),
    ]
