# Generated by Django 3.2.15 on 2022-10-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0007_remove_nurseprofile_year_qualified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='specialty',
            field=models.IntegerField(choices=[(1, 'Ischemic Heart Disease'), (2, 'Heart Failure'), (3, 'Coronary Care'), (4, 'Arrythmia'), (5, 'Congenital Heart Disease'), (6, 'Other')], default=1),
        ),
    ]
