# Generated by Django 3.2.15 on 2022-10-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0008_auto_20221013_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='nurse_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
