# Generated by Django 3.2.15 on 2022-10-14 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0009_auto_20221014_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
