# Generated by Django 3.2.15 on 2022-11-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cardiacnurseprofile', '0009_alter_nurseprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseprofile',
            name='profile_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
