# Generated by Django 3.2.15 on 2022-10-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0010_nurseprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseprofile',
            name='slug',
            field=models.SlugField(),
        ),
    ]
