# Generated by Django 3.2.15 on 2022-11-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardiacnurseprofile', '0010_nurseprofile_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseprofile',
            old_name='profile_owner',
            new_name='profile_creator',
        ),
    ]
